### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by issar13** [alexandear/import-gitlab-commits#1]
is:issue is:open can't do anything with the set of given instructions, I managed to figure out what to do but it throws error at getting current user.

**Comment by alexandear** [comment]
You could try to increase `runTimeout` at the file `cmd/cmd.go` https://github.com/alexandear/import-gitlab-commits/blob/main/cmd/cmd.go#L16

**Comment by Paul-Bob** [comment]
@issar13 did you solve it?

**Comment by issar13** [comment]
still gave the same error.

**Comment by PdoubleU** [comment]
All works fine, the error mentioned here might be a wrong base url

**Comment by Paul-Bob** [comment]
> All works fine, the error mentioned here might be a wrong base url

I don't think so, when you put a wrong base url the error is `dial tcp: lookup gitlab.wrong_url.com: no such host`

**Comment by PdoubleU** [comment]
In some scenarios, yes, it will triger wrong url - but if totally wrong host is provided. However, if the host is corret, but provided path redirects to unavailable source, it's throwing that exceeded-something error. Base url for gitlab nowadays is gitlab.com, and that worked for me. Trying to add path to my account caused context exceeded - like gitlab.com/myaccount

**Comment by Paul-Bob** [comment]
> Base url for gitlab nowadays is gitlab.com, and that worked for me. Trying to add path to my account caused context exceeded - like gitlab.com/myaccount

I put `export GITLAB_BASE_URL=https://gitlab.com` and it finally worked... But in the documentation says to put `export GITLAB_BASE_URL=https://gitlab.yourcompany.com` so i added `.my_company_name` between `gitlab` and `.com` there was the issue!

Now i have a diferent issue, after commited to github, it apear as only 1 commit...
![image](https://user-images.githubusercontent.com/69730720/179322576-42299e89-87ab-4a4b-8640-51f414c34095.png)

 But in this graph from the repository that i just pushed it's clear that there are a lot of commits 
![image](https://user-images.githubusercontent.com/69730720/179322495-f1173277-4c7f-423b-a5a5-64e92dfc37f9.png)
