### ISSUE TITLE
Environment Variables help

### ISSUE THREAD

**Issue by TejAllam** [alexandear/import-gitlab-commits#16]
Hi! Thanks for this.

I'm new to GO, where do I set the environment variables ? 
It doesn't pick up from my profile. 

Can I just overwrite them in the code and build ?

**Comment by alexandear** [comment]
Hi @TejAllam, thanks for the feedback.

Environment variables are set in an operating system. You could read [the article](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html) about how to configure environment variables in different systems.

Of course, it's possible to change the code and rebuild the application. Look for `os.Getenv` lines in the `main.go`.

**Comment by TejAllam** [comment]
Hey thanks for that @alexandear . 
I was able to get the program to run.


But, I only get to see a few in my .git folder using 'git log' command :
![image](https://user-images.githubusercontent.com/16512061/231900833-9a479ea6-3da3-4f8f-8880-180fa93dbe7c.png)

Do I need to have any elevated GitLab API access to fetch all of my commits ?

**Comment by TejAllam** [comment]
Also, I have more than a decade of project histories not necessarily in GitLab; 
Can I theoretically extract, aggregate all my git commits logs based on **Author** and upload them in a similar fashion to GitHub?

**Comment by alexandear** [comment]
> Also, I have more than a decade of project histories not necessarily in GitLab;
Can I theoretically extract, aggregate all my git commits logs based on Author and upload them in a similar fashion to GitHub?

@TejAllam nope, currently it's not possible. `import-gitlab-commits` works only with GitLab.
