### ISSUE TITLE
main.go:14: get current user: get current user: context deadline exceeded

### ISSUE THREAD

**Issue by Paul-Bob** [alexandear/import-gitlab-commits#2]
I'm setting everything up by the guide and keep receiving this error ```18:57:27 main.go:14: get current user: get current user: context deadline exceeded``` any clue how to solve it?

**Comment by vikashcodes** [comment]
@Paul-Bob  i am facing the same issue can you let me know how you fixed it.

**Comment by Paul-Bob** [comment]
@vikashcodes check this issue https://github.com/alexandear/import-gitlab-commits/issues/1 it might be useful

**Comment by vikashcodes** [comment]
I have tried but all in vain.
