### ISSUE TITLE
i'm having difficulty running this tool

### ISSUE THREAD

**Issue by balotofi** [alexandear/import-gitlab-commits#4]
i installed go (armx64)
opened terminal on my mac
checked the version to ensure it was working
i cd to my go folder and ran the report and run commands

**Comment by alexandear** [comment]
Thank you for letting me know about the difficulty you are experiencing running the tool. I'd be happy to assist you with this issue. Could you please provide me with some additional information?

- Can you provide the specific error message or behavior you are experiencing when attempting to run the tool?
- Could you please share the exact commands you ran in the terminal when attempting to run the tool, including any flags or arguments used?
- Additionally, could you please provide any logs or error messages that were generated when you tried to run the tool?

With this information, I'll be better able to diagnose the issue and provide you with a solution.

**Comment by alexandear** [comment]
I see. Try to install `import-gitlab-commits` first:
```shell
go install github.com/alexandear/import-gitlab-commits@latest
```
and execute:
```shell
import-gitlab-commits
```

Or run the following command with `go run`:
```shell
go run github.com/alexandear/import-gitlab-commits@latest
```

**Comment by AlfinIndrawan** [comment]
i have the same problem like that. when i run without export it will give this

10:50:35 main.go:14: Error: app run: get current user: get current user: GET https://gitlab.com/users/sign_in: 403 failed to parse unknown error format

when i run with export like
export GITLAB_BASE_URL=url
export GITLAB_TOKEN="token"
export COMMITTER_NAME="name"
export COMMITTER_EMAIL="email"
go run import-gitlab-commits

it will give error
cannot find package "import-gitlab-commits" in:
	/usr/local/go/src/import-gitlab-commits

**Comment by kubk** [comment]
@alexandear Thank you for the useful package! Unfortunately, the command from the README didn't work for me, so I had to use `go run github.com/alexandear/import-gitlab-commits@latest` to get things running. 

Otherwise, I get this error: 
```bash
./import.sh: line 8: import-gitlab-commits: command not found
```

Should the README be updated?

**Comment by alexandear** [comment]
@kubk thanks, updated README.

Also, you could extend `PATH` with `$GOPATH/bin` and `import-gitlab-commits` will work:
```
export PATH=$PATH:$(go env GOPATH)/bin
```

https://go.dev/doc/gopath_code#GOPATH
